name             'sandy-influxdb'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures sandy-influxdb'
long_description 'Installs/Configures sandy-influxdb'
version          '0.1.0'

depends 'influxdb'
depends 'chef-vault'