name 'sandy-avhrr'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sandy-avhrr'
long_description 'Installs/Configures sandy-avhrr'
version '0.4.0'

depends 'polar2grid'
depends 'nfs'