name             'sandy-dev'
maintainer       'UAFGINA'
maintainer_email 'scott@gina.alaska.edu'
license          'All rights reserved'
description      'Installs/Configures sandy-dev'
long_description 'Installs/Configures sandy-dev'
version          '0.1.0'

depends 'yum-gina'
depends 'postgresql'
depends 'database'
depends 'user'
depends 'chruby'
