name             'sandy-worker'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures sandy-worker'
long_description 'Installs/Configures sandy-worker'
version          '0.1.0'

depends 'sandy'
depends 'lvm'