name             'sandy-ldm'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures sandy-ldm'
long_description 'Installs/Configures sandy-ldm'
version          '0.4.0'

depends 'ldm'
depends 'nginx'
depends 'runit'
depends 'rubies'
