source "https://supermarket.chef.io"

cookbook 'yum-gina', git: 'git@github.com:gina-alaska/yum-gina-cookbook'
cookbook 'chruby'
cookbook 'lvm'
cookbook 'gina-gluster', git: 'git@github.com:gina-alaska/gina-gluster-cookbook'
cookbook 'runit'
cookbook 'build-essential'

metadata
