name             'sandy-landfall'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures sandy-landfall'
long_description 'Installs/Configures sandy-landfall'
version          '0.2.1'

depends 'lvm'
depends 'yum-gina'
depends 'chruby'
depends 'gina-gluster'
depends 'runit'
depends 'build-essential'