source "https://supermarket.getchef.com"

cookbook 'iptables-ng'
cookbook 'chruby'
cookbook 'ntp'
cookbook 'resolver'
cookbook 'chef-client'
cookbook 'postgresql'
cookbook 'redisio'
cookbook 'openssh'
cookbook 'logrotate', '~> 1.6.0'

cookbook 'sandy-dhcp', path: 'cookbooks/sandy-dhcp'
cookbook 'sandy-chef-server', path: 'cookbooks/sandy-chef-server'
cookbook 'cspp', github: 'gina-alaska/cspp-cookbook'
cookbook 'rtstps', github: 'gina-alaska/rtstps-cookbook'
cookbook 'sandy', path: 'cookbooks/sandy-rails'
cookbook 'yum-gina', git: 'git@github.com:gina-alaska/yum-gina-cookbook'
cookbook 'polar2grid', github: 'gina-alaska/polar2grid-cookbook'
cookbook 'gina-gluster', git: 'git@github.com:gina-alaska/gina-gluster-cookbook'
cookbook 'sandy-sudoers', path: 'cookbooks/sandy-sudoers'
