name             'sandy-db'
maintainer       'UAF GINA'
maintainer_email 'support+chef@gina.alaska.edu'
license          'MIT'
description      'Installs/Configures sandy-db'
long_description 'Installs/Configures sandy-db'
version          '0.1.0'

depends 'sandy'
depends 'lvm'
depends 'xfs'
depends 'parted'